Repository ichiro-its/tachimawari, pull requests merged in 2021-03, with the labels that each got.

#2 write this package
  CMakeLists.txt
  CONTRIBUTING.md
  LICENSE
  include/motion/serial.hpp
  package.xml
  src/broadcast_ping_main.cpp
  src/motion/serial.cpp
Labels: enhancement

#6 Add build and test CI
  .github/workflows/ros2-ci.yml
Labels: enhancement

#7 Change the broadcast_ping Name to check_joints
  CMakeLists.txt
  include/motion/serial.hpp
  package.xml
  src/broadcast_ping_main.cpp
  src/check_joints_main.cpp
  src/motion/serial.cpp
Labels: enhancement

#11 create joint class
  motion_opencr/include/motion/joint.hpp
  motion_opencr/src/motion/joint.cpp
Labels: enhancement

#13 Create a program to set the position of servo
  motion_opencr/CMakeLists.txt
  motion_opencr/include/motion/joint.hpp
  motion_opencr/package.xml
  motion_opencr/src/check_joints_main.cpp
  motion_opencr/src/drive_joint_main.cpp
  motion_opencr/src/motion/joint.cpp
Labels: enhancement

#15 fix check joints print out
  motion_opencr/src/check_joints_main.cpp
Labels: bug

#17 Revise motion
  motion_opencr/CMakeLists.txt
  motion_opencr/include/motion_opencr/joint.hpp
  motion_opencr/package.xml
  motion_opencr/src/motion_opencr/joint.cpp
  motion_opencr/src/move_joint_main.cpp
Labels: bug

#19 Create motion manager
  motion_opencr/CMakeLists.txt
  motion_opencr/include/motion_opencr/motion_manager.hpp
  motion_opencr/src/motion_opencr/motion_manager.cpp
Labels: enhancement

#21 Create `move_joint(s)` function
  motion_opencr/include/motion_opencr/joint.hpp
  motion_opencr/include/motion_opencr/motion_manager.hpp
  motion_opencr/src/motion_opencr/joint.cpp
  motion_opencr/src/motion_opencr/motion_manager.cpp
  motion_opencr/src/move_joint_main.cpp
Labels: enhancement

#24 Add sync and bulk function
  motion_opencr/include/motion_opencr/joint.hpp
  motion_opencr/include/motion_opencr/motion_manager.hpp
  motion_opencr/src/motion_opencr/joint.cpp
  motion_opencr/src/motion_opencr/motion_manager.cpp
Labels: enhancement

#25 Create service node and its interfaces
  motion_opencr/CMakeLists.txt
  motion_opencr/include/motion_opencr/motion_manager.hpp
  motion_opencr/package.xml
  motion_opencr/src/motion_opencr/motion_manager.cpp
  motion_opencr_interfaces/CMakeLists.txt
  motion_opencr_interfaces/msg/Joint.msg
  motion_opencr_interfaces/package.xml
  motion_opencr_interfaces/srv/SetJoints.srv
Labels: enhancement

#29 change project name to tachimawari
  tachimawari/CMakeLists.txt
  tachimawari/include/tachimawari/joint.hpp
  tachimawari/include/tachimawari/motion_manager.hpp
  tachimawari/package.xml
  tachimawari/src/check_joints_main.cpp
  tachimawari/src/move_joint_main.cpp
  tachimawari/src/tachimawari/joint.cpp
  tachimawari/src/tachimawari/motion_manager.cpp
  tachimawari_interfaces/CMakeLists.txt
  tachimawari_interfaces/msg/Joint.msg
  tachimawari_interfaces/package.xml
  tachimawari_interfaces/srv/SetJoints.srv
Labels: documentation, enhancement

#30 4 add readme
  .github/workflows/build-and-test.yml
  .github/workflows/ros2-ci.yml
  LICENSE
  README.md
  tachimawari/package.xml
  tachimawari_interfaces/package.xml
Labels: documentation

#33 Separate the projects
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  include/tachimawari/joint.hpp
  include/tachimawari/motion_manager.hpp
  package.xml
  src/check_joints_main.cpp
  src/motion_manager_main.cpp
  src/move_joint_main.cpp
  src/tachimawari/joint.cpp
  src/tachimawari/motion_manager.cpp
  tachimawari_interfaces/CMakeLists.txt
  tachimawari_interfaces/msg/Joint.msg
  tachimawari_interfaces/package.xml
  tachimawari_interfaces/srv/SetJoints.srv
Labels: enhancement, good first issue
